CREATE TABLE TASKS (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    TASK_DATE DATE NOT NULL
);

INSERT INTO TASKS (ID, DESCRIPTION, TASK_DATE) VALUES (1, 'Task 1', '2022-03-02');
INSERT INTO TASKS (ID, DESCRIPTION, TASK_DATE) VALUES (2, 'Task 2', '2022-03-05');
